### ISSUE TITLE
create subdirectories

### ISSUE THREAD

**Issue by gchenhub** [uml-ubicomp-2016-spring/ubicomp16-GPSCollector#1]
create app directory for Duo Liu, and data analysis directories separately

**Comment by deercoder** [comment]
Fixed @[70c2](https://github.com/uml-ubicomp-2016-spring/ubicomp16-GPSCollector/commit/70c27743c41c7bdbc243ba91422fda554f7668ac), @[263f](https://github.com/uml-ubicomp-2016-spring/ubicomp16-GPSCollector/commit/263f4fb2d71224be39f7c56f0afad366cb17c170)
